### PR TITLE
Test cases and bugs fixed for lswardpat

### LINKED ISSUE #174: [PE-D][Tester C] No response `trfward 2 w/block a` where 2 is the index of staff
step to generate the bug: 

1. lsstf
2. trfward 2 w/block a

no response or error message displayed 

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: gmengqi/ped#9

### PR DESCRIPTION
**Pull request by GlennOngJunJie**
lswardpat fixed, other issue did not have any problems. 
Further Improve test cases for lswardpat and lswardstf

Fixes #174

### CODE REVIEW

**Review by pzhengze — CHANGES_REQUESTED** [review]
I think we should make the function be able to transfer staff as well like we originally intended in the ug instead of removing any capability of transferring staff.

Remove the casting without any checking here.
image
Shift this section up and check with containsPerson 
image
and only at this section do you check for patient or staff and call the appropriate transfer command
image

File: src/main/java/seedu/patientist/logic/commands/UpdateWardCommand.java [hunk 1]
```diff
@@ -29,7 +31,8 @@ public class UpdatePatientWardCommand extends Command {
 
     public static final String MESSAGE_SUCCESS = "Patient %1$s has been transferred from ward %2$s to ward %3$s";
     public static final String MESSAGE_WARD_NOT_FOUND = "Ward not found: %1$s";
-    public static final String MESSAGE_WARD_INCORRECT = "Ward of patient is incorrect";
+    public static final String MESSAGE_WARD_INCORRECT = "New ward of patient is incorrect";
```
Comment (pzhengze) [inline src/main/java/seedu/patientist/logic/commands/UpdateWardCommand.java:34]: change patient to person

File: src/main/java/seedu/patientist/logic/commands/UpdateWardCommand.java [hunk 2]
```diff
@@ -12,13 +12,15 @@
...
 
 /**
  * Update Patient's ward identified using it's displayed index from the patientist book.
  */
 
-public class UpdatePatientWardCommand extends Command {
+public class UpdateWardCommand extends Command {
     public static final String COMMAND_WORD = "trfward";
 
     public static final String MESSAGE_USAGE = COMMAND_WORD + ": Moves the patient."
```
Comment (pzhengze) [inline src/main/java/seedu/patientist/logic/commands/UpdateWardCommand.java:26]: Change this to `Transfers the person indicated by the index to the ward specified. `. Remember to add a space after the fullstop.

**Review by pzhengze — APPROVED** [review]
Looks fine. Just need some changes to the messages
